"""Shared state models for AI Marketing Agency pipelines.

This module defines Pydantic models representing the mutable
state passed between agents in the base and client pipelines.
Each class provides type hints and sensible defaults for the
expected data collected or produced by the agents.
"""
from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class BasePipelineState(BaseModel):
    """State object passed through the Base Team pipeline.

    Attributes:
        sales_manager: Status or result from the sales manager agent.
        prospects: A list of prospect identifiers sourced by the prospector.
        outreach: Status from the outreach specialist (e.g., "emails_sent").
        appointments: Meetings scheduled by the appointment setter.
        proposal: Proposal content generated by the proposal builder.
        compliance: Result of QA/compliance check (True if compliant, False otherwise).
    """

    sales_manager: Optional[str] = None
    prospects: List[str] = Field(default_factory=list)
    outreach: Optional[str] = None
    appointments: List[str] = Field(default_factory=list)
    proposal: Optional[str] = None
    compliance: Optional[bool] = None


class ClientPipelineState(BaseModel):
    """State object passed through the Client Team pipeline.

    Attributes:
        client_name: Name of the client associated with this pipeline.
        account_manager: Status or actions taken by the account manager.
        growth_strategy: Strategy drafted by the growth strategist.
        funnel: Funnel architecture designed by the funnel architect.
        creatives: List of creative assets produced by the creative director.
        media_plan: Media plan created or simulated by the media buyer.
        ads_compliance: Result of ads compliance QA (True if compliant).
    """

    client_name: Optional[str] = None
    account_manager: Optional[str] = None
    growth_strategy: Optional[str] = None
    funnel: Optional[str] = None
    creatives: List[str] = Field(default_factory=list)
    media_plan: Optional[str] = None
    ads_compliance: Optional[bool] = None


__all__ = ["BasePipelineState", "ClientPipelineState"]
